// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANKolRt3VFfcRLr9W5NLy-rxouldyD6yM',
    appId: '1:303537348027:web:061b792f28ecd57b5a389e',
    messagingSenderId: '303537348027',
    projectId: 'medsync-19c28',
    authDomain: 'medsync-19c28.firebaseapp.com',
    storageBucket: 'medsync-19c28.firebasestorage.app',
    measurementId: 'G-BD7T4K1T9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUO_9_l5YzP8bum7eDS81SRO6pGIF32g0',
    appId: '1:303537348027:android:8efd9fdce0d886155a389e',
    messagingSenderId: '303537348027',
    projectId: 'medsync-19c28',
    storageBucket: 'medsync-19c28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtJFLGwBoWdf8--XNIGcdemG1V3M4gAMc',
    appId: '1:303537348027:ios:e7b9da35a7295bf45a389e',
    messagingSenderId: '303537348027',
    projectId: 'medsync-19c28',
    storageBucket: 'medsync-19c28.firebasestorage.app',
    iosBundleId: 'com.example.medSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtJFLGwBoWdf8--XNIGcdemG1V3M4gAMc',
    appId: '1:303537348027:ios:e7b9da35a7295bf45a389e',
    messagingSenderId: '303537348027',
    projectId: 'medsync-19c28',
    storageBucket: 'medsync-19c28.firebasestorage.app',
    iosBundleId: 'com.example.medSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANKolRt3VFfcRLr9W5NLy-rxouldyD6yM',
    appId: '1:303537348027:web:06b98d4d12aeb9b45a389e',
    messagingSenderId: '303537348027',
    projectId: 'medsync-19c28',
    authDomain: 'medsync-19c28.firebaseapp.com',
    storageBucket: 'medsync-19c28.firebasestorage.app',
    measurementId: 'G-NKB4714CWV',
  );
}
